describe('Exercícios 21–40 (TODOs)', () => {
  test.todo('21. Implementar versionamento otimista em Product e updateIfVersion')
  test.todo('22. Batch de atualização de estoque atômico em transação SQLite')
  test.todo('23. Mapeador toOrderDTO usando Omit/Pick e normalização de datas')
  test.todo('24. Inferir tipos de DTOs a partir de schemas zod nas rotas HTTP')
  test.todo('25. Tornar listagem de produtos ReadonlyArray e impedir mutações')
  test.todo('26. Cache LRU genérico <K,V> com política de ejeção')
  test.todo('27. Métricas via interface Metrics (in-memory e no-op)')
  test.todo('28. Eventos de domínio assíncronos com Promise.allSettled')
  test.todo('29. Type guard isOrder(obj: unknown): obj is Order')
  test.todo('30. Modelar CheckoutFailure rico com code/message/recoverable')
  test.todo('31. Uso de never para exaustividade em switch de frete')
  test.todo('32. Serializer determinístico de Order e snapshot test')
  test.todo('33. Módulo money.ts (centavos) com branded type Money')
  test.todo('34. parseEnv com zod e fallback seguros')
  test.todo('35. withTransaction(db, fn) tipado e seguro a rollback')
  test.todo('36. const enum para códigos de erro (trade-offs)')
  test.todo('37. Fluxo de reembolso com eventos e invariantes')
  test.todo('38. Benchmark simples do PriceCalculator')
  test.todo('39. Teste de carga fake para checkout e medição')
  test.todo('40. DeepReadonly<T> e aplicação em Order retornada')
})
